# This is a basic workflow to help you get started with Actions

name: Workflow Dispatch for Hugo Page

run: |
curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/traceofahuman/blog/actions/workflows/build.yaml/dispatches --data '{"ref": "master"}'
