# This is a basic workflow to help you get started with Actions

name: Workflow Dispatch for Hugo Page

on:
  push:
    branches: 
      - main
  # Allows manual trigger
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Fire Dispatch Event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: <username>/<repository>
          event-type: update
