# This is a basic workflow to help you get started with Actions

name: Workflow Dispatch for Hugo Page

on:
  push:
    branches: 
      - main

jobs:
  trigger-event:
    runs-on: ubuntu-latest
    steps:
      - name: Fire Dispatch Event
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.BLOG_POST_TRIGGER }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/traceofahuman/blog/dispatches \
            -d '{"event_type":"dispatch-event"}'
